### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.3

### PR DESCRIPTION
**Pull request by jdblischak**

### CODE REVIEW

**Comment by jdblischak** [comment]
@jsignell Could you please review and merge this PR? It rerenders the feedstock so that r-circstats will be built with R 3.4.1 for Windows. Thanks!

**Comment by jdblischak** [comment]
@jsignell Could you please click Merge pull request? You are the only maintainer listed on this recipe, so only you can merge this maintenance PR.

**Comment by ocefpaf** [comment]
@jdblischak consider adding yourself as a maintainer here.

**Comment by jdblischak** [comment]
> consider adding yourself as a maintainer here.

@ocefpaf Yes, that will happen in a future pass when I update the conda-forge R recipes. Right now I am trying to rerender all the R feedstocks that need to be rerendered. Thanks for merging!

**Pull request merged**
